version: "3.8"

services:
  web:
    build: .
    container_name: ecommerce_backend
    restart: always

    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

