version: "3.8"

services:
  
  celery:
    build: .
    container_name: celery_worker
    command: sh -c "DJANGO_SETTINGS_MODULE=ecommerce_service.settings celery -A ecommerce_service worker --loglevel=info"
    volumes:
      - .:/app
    env_file:
      - .env
    network_mode: "host"
   

  